"use client";

/**
 * components/journey/multi-day-itinerary-panel.tsx
 *
 * Phase 3 upgrade: Each "travel" segment now shows a collapsible row of
 * booking deep-links auto-generated by the booking-engine based on the
 * segment text (train / flight / bus / cab classifier).
 *
 * Backward compatible — existing non-travel segments show no booking links.
 */

import { useState } from "react";
import {
  ChevronDown,
  ChevronUp,
  Train,
  Camera,
  Utensils,
  Coffee,
  Shield,
  MapPin,
  Ticket,
} from "lucide-react";
import { BookingButton } from "@/components/ui/BookingButton";
import {
  getSegmentBookingLinks,
  type UniversalSegmentParams,
} from "@/services/booking-engine";
import { useTripIntent, useCurrency } from "@/hooks/useTripStore";

interface ItinerarySegment {
  time: string;
  activity: string;
  description: string;
  type: "travel" | "attraction" | "food" | "rest" | "safety" | string;
  location: string;
}

interface ItineraryDay {
  dayNumber: number;
  date?: string;
  segments: ItinerarySegment[];
  accommodation?: { name: string; type: string; estimatedCostPerNight?: number };
  notes?: string;
}

interface MultiDayItineraryPanelProps {
  days: ItineraryDay[];
}

function SegmentIcon({ type }: { type: string }) {
  const cls = "w-4 h-4 flex-shrink-0 text-primary";
  switch (type) {
    case "travel":     return <Train className={cls} />;
    case "attraction": return <Camera className={cls} />;
    case "food":       return <Utensils className={cls} />;
    case "rest":       return <Coffee className={cls} />;
    case "safety":     return <Shield className={cls} />;
    default:           return <MapPin className={cls} />;
  }
}

export function MultiDayItineraryPanel({ days }: MultiDayItineraryPanelProps) {
  const [openDay, setOpenDay] = useState<number>(1);
  const [openBooking, setOpenBooking] = useState<string | null>(null); // "day-segIdx"

  const intent = useTripIntent();
  const currency = useCurrency();

  // Trip-level context for the booking engine
  const tripFrom        = intent?.from ?? "";
  const tripTo          = intent?.to ?? "";
  const tripDate        = intent?.departureDate ?? new Date().toISOString().slice(0, 10);
  const tripReturnDate  = intent?.returnDate;
  const tripPassengers  = intent?.travellers ?? 1;

  if (!days || days.length === 0) {
    return (
      <div className="rounded-xl bg-white/5 border border-white/10 p-4 text-sm text-foreground/50 text-center">
        No itinerary available yet. Plan your trip to see day-by-day details.
      </div>
    );
  }

  return (
    <div className="flex flex-col gap-2">
      {days.map((day) => (
        <div key={day.dayNumber} className="rounded-xl bg-white/5 border border-white/10 overflow-hidden">
          {/* Day header */}
          <button
            className="w-full flex items-center justify-between px-4 py-3 hover:bg-white/5 transition-colors"
            onClick={() => setOpenDay(openDay === day.dayNumber ? -1 : day.dayNumber)}
            aria-expanded={openDay === day.dayNumber}
          >
            <div className="flex items-center gap-3">
              <span className="text-xs font-medium bg-primary/20 text-primary px-2 py-0.5 rounded-full">
                Day {day.dayNumber}
              </span>
              {day.date && (
                <span className="text-xs text-foreground/50">{day.date}</span>
              )}
              <span className="text-sm text-foreground/70">
                {day.segments.length} stop{day.segments.length !== 1 ? "s" : ""}
              </span>
            </div>
            {openDay === day.dayNumber
              ? <ChevronUp size={16} className="text-foreground/50" />
              : <ChevronDown size={16} className="text-foreground/50" />
            }
          </button>

          {/* Day content */}
          {openDay === day.dayNumber && (
            <div className="px-4 pb-4">
              {/* Timeline */}
              <div className="flex flex-col gap-0">
                {day.segments.map((seg, idx) => {
                  const bookingKey = `${day.dayNumber}-${idx}`;
                  const isBookingOpen = openBooking === bookingKey;

                  // Generate booking links for travel segments
                  let bookingLinks = [] as ReturnType<typeof getSegmentBookingLinks>;
                  if (seg.type === "travel" && tripFrom && tripTo) {
                    const params: UniversalSegmentParams = {
                      activity: seg.activity,
                      description: seg.description,
                      location: seg.location,
                      type: seg.type,
                      tripFrom,
                      tripTo,
                      tripDate,
                      tripReturnDate,
                      tripPassengers,
                      tripCurrency: currency,
                    };
                    bookingLinks = getSegmentBookingLinks(params);
                  }

                  return (
                    <div key={idx} className="flex gap-3 relative">
                      {/* Timeline line */}
                      {idx < day.segments.length - 1 && (
                        <div className="absolute left-[11px] top-7 bottom-0 w-px bg-white/10" />
                      )}
                      <div className="flex flex-col items-center pt-1">
                        <div className="w-6 h-6 rounded-full bg-white/10 flex items-center justify-center flex-shrink-0">
                          <SegmentIcon type={seg.type} />
                        </div>
                      </div>
                      <div className="flex-1 pb-4 min-w-0">
                        <div className="flex items-baseline gap-2">
                          <span className="text-xs text-primary font-mono">{seg.time}</span>
                          <span className="text-sm font-medium text-foreground">{seg.activity}</span>
                        </div>
                        <p className="text-xs text-foreground/60 mt-0.5">{seg.description}</p>
                        <span className="text-xs text-foreground/40 mt-1 inline-block">📍 {seg.location}</span>

                        {/* Phase 3 — Booking Links for travel segments */}
                        {bookingLinks.length > 0 && (
                          <div className="mt-2">
                            <button
                              onClick={() => setOpenBooking(isBookingOpen ? null : bookingKey)}
                              className="inline-flex items-center gap-1.5 text-xs text-brand-cyan/80 hover:text-brand-cyan transition-colors"
                              aria-expanded={isBookingOpen}
                            >
                              <Ticket className="w-3 h-3" />
                              {isBookingOpen ? "Hide booking options" : `Book this leg ↓`}
                            </button>

                            {isBookingOpen && (
                              <div className="mt-2 flex flex-wrap gap-1.5">
                                {bookingLinks.map((link) => (
                                  <BookingButton key={link.platform} link={link} size="sm" />
                                ))}
                              </div>
                            )}
                          </div>
                        )}
                      </div>
                    </div>
                  );
                })}
              </div>

              {/* Accommodation note */}
              {day.accommodation && (
                <div className="mt-2 rounded-lg bg-white/5 border border-white/5 px-3 py-2 flex items-center gap-2">
                  <span className="text-xs text-foreground/50">🏨 Stay:</span>
                  <span className="text-xs text-foreground">{day.accommodation.name}</span>
                  {day.accommodation.estimatedCostPerNight && (
                    <span className="text-xs text-foreground/40 ml-auto">
                      ~{currency} {day.accommodation.estimatedCostPerNight.toLocaleString("en-IN")}/night
                    </span>
                  )}
                </div>
              )}

              {/* Day notes */}
              {day.notes && (
                <p className="mt-2 text-xs text-foreground/40 italic">{day.notes}</p>
              )}
            </div>
          )}
        </div>
      ))}
    </div>
  );
}
